
# Numpy

## Why numpy ?? 

* Faster to read since no typeschecking needed for numpy array because all are same type
* Native array is faster than list
* Contiguous memory allocation unlike list

In [2]:
import numpy as np

In [9]:
a = np.array([1,2,4])
print(a)

[1 2 4]


In [79]:
# multidimension array 
b = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
# array shape
b.shape 

(2, 5)

In [45]:
# array dimensions 
b.ndim

2

In [46]:
# array data type
b.dtype

dtype('int64')

In [47]:
# Elements size in array
b.itemsize

8

In [48]:
# Total elements in array 
b.size

10

In [49]:
# Total array size
b.size * a.itemsize 

20

In [50]:
# Total array size
b.nbytes

80

In [52]:
# manually defining data type
a = np.array([1,2,4,5] , dtype= 'int16')
a.itemsize 

2

In [53]:
# Get specific item 
b[1][1] 

6

In [56]:
# Get specific item with negative index 
b[1][-1]  # -1 represents first element from last

9

In [54]:
# Get specific row
b[0 , :]

array([0, 1, 2, 3, 4])

In [57]:
# Get specific column
b[ : , 0]

array([0, 5])

In [62]:
# get numbers leaving steps 
b[0 , 0:5:2]

array([0, 2, 4])

In [68]:
# updating single number
b[0,0] = 100
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [70]:
# updating single row
b[0,:] = 100
b

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [ ]:
# updating single column
b[:,0] = 100
b

## 3D Arrays

In [82]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [88]:
# All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [91]:
# All 1s matrix
np.ones((3,3,3) , dtype="int16")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [94]:
# initialize with any other number
np.full((2,2,2), 66 , dtype="int32")

array([[[66, 66],
        [66, 66]],

       [[66, 66],
        [66, 66]]], dtype=int32)

In [97]:
# initializing already existing array with  value
np.full_like(a , 5)

array([5, 5, 5, 5], dtype=int16)

In [99]:
#initialize with random float numbers between 0 and 1.
np.random.rand(2,4)

array([[0.9885468 , 0.85141643, 0.95548073, 0.92585173],
       [0.38005048, 0.9496109 , 0.26293787, 0.15084124]])

In [101]:
# if want to initialize with shape (shape is tuple)
np.random.random_sample(b.shape)

array([[0.08885384, 0.6167025 , 0.31878466, 0.05802974, 0.69896544],
       [0.35157304, 0.9239081 , 0.71428129, 0.60658471, 0.78479314]])

In [103]:
# Random int values if no parameters passed returns single  value
np.random.randint(7,size = (4,4)) #  7 here is upper limit

array([[1, 0, 2, 4],
       [5, 1, 0, 3],
       [1, 6, 6, 5],
       [2, 0, 0, 1]])

## Do you really have to remember all these methods 😖, & their parameters ??
#### The answer is **NO** , for e.g if you want to know about `np.random.randint` method type `np.random.randint?` to print the docstring .


In [108]:
# Random int values with lower and upper  limit
np.random.randint(-3,8,size = (4,4)) 

array([[-2,  4,  6,  7],
       [ 0, -3,  6,  2],
       [ 7,  2, -3,  1],
       [ 4, -3, -2,  2]])

In [111]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
# repeat numbers in array
arr = np.array([1,2,4]) # 1D array have only 1 axis
np.repeat(arr , 3)

array([1, 1, 1, 2, 2, 2, 4, 4, 4])

In [121]:
# repeat numbers in array
arr = np.array([[1,2,4]]) # 2D matrix have 2 axis 
np.repeat(arr , 3, axis=0) # repeat but not on same axis

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

### You should avoid copying arrays directly !!! , see why 🤓

#### Incorrect way  👎

In [131]:
a = np.array([1,2,3])
b = a
b[0] = 100 # changing element in copied array
a[0]  # it changed in original array too 🤯

100

#### Correct Way  👍 

In [135]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 # changing copied array
a[0]  # original array is same

1

## Mathematics

In [137]:
a = np.array([1,2,3])
print("add", a + 2)
print("multiply",a * 2)
print("divide",a / 2)
print("subtract",a - 2)

add [3 4 5]
multiply [2 4 6]
divide [0.5 1.  1.5]
subtract [-1  0  1]


In [141]:
#  operation between arrays (arithmatic opertion will be on corresponding elements)
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a -b )
print(a  + b )
print(a  / b )
print(a * b )

[-3 -3 -3]
[5 7 9]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [143]:
# square all elements in array
a = np.array([1,2,3])
a**2

array([1, 4, 9])

In [147]:
# sine, cosine,etc of array elements
a = np.array([1,2,3])

print(np.cos(a))
print(np.sin(a))


[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]


## Linear Algebra

In [7]:
a = np.ones((2,3))
print("a is \n" , a)
b = np.full((3,2), 3)
print("b is \n" , b)

print("a * b is \n" , np.matmul(a,b))



a is 
 [[1. 1. 1.]
 [1. 1. 1.]]
b is 
 [[3 3]
 [3 3]
 [3 3]]
a * b is 
 [[9. 9.]
 [9. 9.]]


In [9]:
# Finding the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statics

In [13]:
arr = np.array([[1,2,3],[4,5,6]]) 
min_value = np.min(arr)
print("min value ",min_value )

max_value = np.max(arr)
print("max value ",max_value )

min value  1
max value  6


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
min_value = np.min(arr , axis = 1) # among (1,4) , (2,3) , (3,6)
print("min value along axis 1",min_value )

max_value = np.max(arr,axis = 1) # among (1,4) , (2,3) , (3,6)
print("max value along axis 1",max_value )

arr = np.array([[1,2,3],[4,5,6]])
min_value = np.min(arr , axis = 0) # between (1,2,3) , (4,5,6)
print("min value along axis 0",min_value )

max_value = np.max(arr,axis = 0) # between (1,2,3) , (4,5,6)
print("max value along axis 0",max_value )

min value along axis 1 [1 4]
max value along axis 1 [3 6]
min value along axis 0 [1 2 3]
max value along axis 0 [4 5 6]


In [21]:
# sum all elemements
arr = np.array([[1,2,3],[4,5,6]])

total_sum = np.sum(arr)
print("Total sum " ,total_sum)

sum_0 = np.sum(arr , axis=0)
sum_1 = np.sum(arr , axis=1)

print("Total sum axis 0 " ,sum_0)
print("Total sum axis 1" ,sum_1)


Total sum  21
Total sum axis 0  [5 7 9]
Total sum axis 1 [ 6 15]


### Reorganizing Array

In [23]:
# resizing vectors
arr = np.array([[1,2,3],[4,5,6]])
arr.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [26]:
# vertical stack vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# horizontal stack
v1  = np.ones((2,4))
v2  = np.ones((2,2))

np.hstack([v1,v2])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Loading data

In [32]:
# data from file
np.genfromtxt('data.txt', delimiter="\n")

array([1., 2., 3., 4., 5., 6., 7.])

In [34]:
# convert datatype of loaded data
np.genfromtxt('data.txt', delimiter="\n").astype('int32')

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

### Boolean Masking & Advanced Indexing

In [3]:
# comparing loaded data
np.genfromtxt('data.txt') > 3

array([False, False, False,  True,  True,  True,  True])

In [6]:
# accessing index 2,5,7 from array at once
arr  = np.array([0,1,2,3,4,5,6,7,8,9])
arr[[2,5,7]]

array([2, 5, 7])

In [10]:
# selecting values in range
arr = np.random.randint(0,100,(4,4), dtype="int32")
print( arr )
((arr > 25 ) & (arr < 75))

[[96 54 79 21]
 [32 32 34 59]
 [58  2 48 10]
 [48 31 32 47]]


array([[False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [24]:
arr = np.arange(1,31).reshape(6,5)
#  getting diagonal elements
arr[[1,2,3,4] , [1,2,3,4]]

array([ 7, 13, 19, 25])